name: Folktale
pygments: true

navigation:
  - text: Overview
    url: /index.html
    group: home
  - text: Documentation
    url: http://folktalegithubio.readthedocs.io/en/latest/
    group: docs
  - text: Community
    url: /community/index.html
    group: community
